repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
      exclude: tests/data
    - id: check-ast
    - id: debug-statements
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-added-large-files
    - id: requirements-txt-fixer
    - id: file-contents-sorter
      files: requirements-dev.txt

- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
    - id: interrogate
      exclude: ^(docs|setup.py|tests)
      args: [--config=pyproject.toml]

- repo: https://github.com/keewis/blackdoc
  rev: v0.3.8
  hooks:
    - id: blackdoc

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.282
  hooks:
    - id: ruff

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
    - id: codespell
      args:
        - --quiet-level=2

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.0.1
  hooks:
    - id: add-trailing-comma

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "0.13.0"
  hooks:
    - id: pyproject-fmt

- repo: https://github.com/aio-libs/sort-all
  rev: "v1.2.0"
  hooks:
    - id: sort-all
      types: [file, python]


ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false
